apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-nginx
  namespace: web-nginx
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/web-nginx
      sourceRef:
        kind: GitRepository
        name: flux-config-03
        namespace: web-nginx
      interval: 1m
  values:
   image: 
    repository: acreastus01.azurecr.io/nginx
    tag: 1.0.1

